/*
 * NiFi Rest Api
 * The Rest Api provides programmatic access to command and control a NiFi instance in real time. Start and                                              stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * OpenAPI spec version: 1.3.0
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.github.hermannpencole.nifi.swagger.client.model;

import java.util.Objects;
import com.github.hermannpencole.nifi.swagger.client.model.CounterDTO;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * CountersSnapshotDTO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-06-15T23:51:49.699+02:00")
public class CountersSnapshotDTO {
  @SerializedName("generated")
  private String generated = null;

  @SerializedName("counters")
  private List<CounterDTO> counters = new ArrayList<CounterDTO>();

  public CountersSnapshotDTO generated(String generated) {
    this.generated = generated;
    return this;
  }

   /**
   * The timestamp when the report was generated.
   * @return generated
  **/
  @ApiModelProperty(example = "null", value = "The timestamp when the report was generated.")
  public String getGenerated() {
    return generated;
  }

  public void setGenerated(String generated) {
    this.generated = generated;
  }

  public CountersSnapshotDTO counters(List<CounterDTO> counters) {
    this.counters = counters;
    return this;
  }

  public CountersSnapshotDTO addCountersItem(CounterDTO countersItem) {
    this.counters.add(countersItem);
    return this;
  }

   /**
   * All counters in the NiFi.
   * @return counters
  **/
  @ApiModelProperty(example = "null", value = "All counters in the NiFi.")
  public List<CounterDTO> getCounters() {
    return counters;
  }

  public void setCounters(List<CounterDTO> counters) {
    this.counters = counters;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CountersSnapshotDTO countersSnapshotDTO = (CountersSnapshotDTO) o;
    return Objects.equals(this.generated, countersSnapshotDTO.generated) &&
        Objects.equals(this.counters, countersSnapshotDTO.counters);
  }

  @Override
  public int hashCode() {
    return Objects.hash(generated, counters);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CountersSnapshotDTO {\n");
    
    sb.append("    generated: ").append(toIndentedString(generated)).append("\n");
    sb.append("    counters: ").append(toIndentedString(counters)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

