/*
 * NiFi Rest Api
 * The Rest Api provides programmatic access to command and control a NiFi instance in real time. Start and                                              stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.github.hermannpencole.nifi.swagger.client.model;

import java.util.Objects;
import com.github.hermannpencole.nifi.swagger.client.model.ConnectionEntity;
import com.github.hermannpencole.nifi.swagger.client.model.FunnelEntity;
import com.github.hermannpencole.nifi.swagger.client.model.LabelEntity;
import com.github.hermannpencole.nifi.swagger.client.model.PortEntity;
import com.github.hermannpencole.nifi.swagger.client.model.ProcessGroupEntity;
import com.github.hermannpencole.nifi.swagger.client.model.ProcessorEntity;
import com.github.hermannpencole.nifi.swagger.client.model.RemoteProcessGroupEntity;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * FlowDTO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-05-30T10:58:58.550+02:00")
public class FlowDTO {
  @SerializedName("processGroups")
  private List<ProcessGroupEntity> processGroups = new ArrayList<ProcessGroupEntity>();

  @SerializedName("remoteProcessGroups")
  private List<RemoteProcessGroupEntity> remoteProcessGroups = new ArrayList<RemoteProcessGroupEntity>();

  @SerializedName("processors")
  private List<ProcessorEntity> processors = new ArrayList<ProcessorEntity>();

  @SerializedName("inputPorts")
  private List<PortEntity> inputPorts = new ArrayList<PortEntity>();

  @SerializedName("outputPorts")
  private List<PortEntity> outputPorts = new ArrayList<PortEntity>();

  @SerializedName("connections")
  private List<ConnectionEntity> connections = new ArrayList<ConnectionEntity>();

  @SerializedName("labels")
  private List<LabelEntity> labels = new ArrayList<LabelEntity>();

  @SerializedName("funnels")
  private List<FunnelEntity> funnels = new ArrayList<FunnelEntity>();

  public FlowDTO processGroups(List<ProcessGroupEntity> processGroups) {
    this.processGroups = processGroups;
    return this;
  }

  public FlowDTO addProcessGroupsItem(ProcessGroupEntity processGroupsItem) {
    this.processGroups.add(processGroupsItem);
    return this;
  }

   /**
   * The process groups in this flow.
   * @return processGroups
  **/
  @ApiModelProperty(example = "null", value = "The process groups in this flow.")
  public List<ProcessGroupEntity> getProcessGroups() {
    return processGroups;
  }

  public void setProcessGroups(List<ProcessGroupEntity> processGroups) {
    this.processGroups = processGroups;
  }

  public FlowDTO remoteProcessGroups(List<RemoteProcessGroupEntity> remoteProcessGroups) {
    this.remoteProcessGroups = remoteProcessGroups;
    return this;
  }

  public FlowDTO addRemoteProcessGroupsItem(RemoteProcessGroupEntity remoteProcessGroupsItem) {
    this.remoteProcessGroups.add(remoteProcessGroupsItem);
    return this;
  }

   /**
   * The remote process groups in this flow.
   * @return remoteProcessGroups
  **/
  @ApiModelProperty(example = "null", value = "The remote process groups in this flow.")
  public List<RemoteProcessGroupEntity> getRemoteProcessGroups() {
    return remoteProcessGroups;
  }

  public void setRemoteProcessGroups(List<RemoteProcessGroupEntity> remoteProcessGroups) {
    this.remoteProcessGroups = remoteProcessGroups;
  }

  public FlowDTO processors(List<ProcessorEntity> processors) {
    this.processors = processors;
    return this;
  }

  public FlowDTO addProcessorsItem(ProcessorEntity processorsItem) {
    this.processors.add(processorsItem);
    return this;
  }

   /**
   * The processors in this flow.
   * @return processors
  **/
  @ApiModelProperty(example = "null", value = "The processors in this flow.")
  public List<ProcessorEntity> getProcessors() {
    return processors;
  }

  public void setProcessors(List<ProcessorEntity> processors) {
    this.processors = processors;
  }

  public FlowDTO inputPorts(List<PortEntity> inputPorts) {
    this.inputPorts = inputPorts;
    return this;
  }

  public FlowDTO addInputPortsItem(PortEntity inputPortsItem) {
    this.inputPorts.add(inputPortsItem);
    return this;
  }

   /**
   * The input ports in this flow.
   * @return inputPorts
  **/
  @ApiModelProperty(example = "null", value = "The input ports in this flow.")
  public List<PortEntity> getInputPorts() {
    return inputPorts;
  }

  public void setInputPorts(List<PortEntity> inputPorts) {
    this.inputPorts = inputPorts;
  }

  public FlowDTO outputPorts(List<PortEntity> outputPorts) {
    this.outputPorts = outputPorts;
    return this;
  }

  public FlowDTO addOutputPortsItem(PortEntity outputPortsItem) {
    this.outputPorts.add(outputPortsItem);
    return this;
  }

   /**
   * The output ports in this flow.
   * @return outputPorts
  **/
  @ApiModelProperty(example = "null", value = "The output ports in this flow.")
  public List<PortEntity> getOutputPorts() {
    return outputPorts;
  }

  public void setOutputPorts(List<PortEntity> outputPorts) {
    this.outputPorts = outputPorts;
  }

  public FlowDTO connections(List<ConnectionEntity> connections) {
    this.connections = connections;
    return this;
  }

  public FlowDTO addConnectionsItem(ConnectionEntity connectionsItem) {
    this.connections.add(connectionsItem);
    return this;
  }

   /**
   * The connections in this flow.
   * @return connections
  **/
  @ApiModelProperty(example = "null", value = "The connections in this flow.")
  public List<ConnectionEntity> getConnections() {
    return connections;
  }

  public void setConnections(List<ConnectionEntity> connections) {
    this.connections = connections;
  }

  public FlowDTO labels(List<LabelEntity> labels) {
    this.labels = labels;
    return this;
  }

  public FlowDTO addLabelsItem(LabelEntity labelsItem) {
    this.labels.add(labelsItem);
    return this;
  }

   /**
   * The labels in this flow.
   * @return labels
  **/
  @ApiModelProperty(example = "null", value = "The labels in this flow.")
  public List<LabelEntity> getLabels() {
    return labels;
  }

  public void setLabels(List<LabelEntity> labels) {
    this.labels = labels;
  }

  public FlowDTO funnels(List<FunnelEntity> funnels) {
    this.funnels = funnels;
    return this;
  }

  public FlowDTO addFunnelsItem(FunnelEntity funnelsItem) {
    this.funnels.add(funnelsItem);
    return this;
  }

   /**
   * The funnels in this flow.
   * @return funnels
  **/
  @ApiModelProperty(example = "null", value = "The funnels in this flow.")
  public List<FunnelEntity> getFunnels() {
    return funnels;
  }

  public void setFunnels(List<FunnelEntity> funnels) {
    this.funnels = funnels;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FlowDTO flowDTO = (FlowDTO) o;
    return Objects.equals(this.processGroups, flowDTO.processGroups) &&
        Objects.equals(this.remoteProcessGroups, flowDTO.remoteProcessGroups) &&
        Objects.equals(this.processors, flowDTO.processors) &&
        Objects.equals(this.inputPorts, flowDTO.inputPorts) &&
        Objects.equals(this.outputPorts, flowDTO.outputPorts) &&
        Objects.equals(this.connections, flowDTO.connections) &&
        Objects.equals(this.labels, flowDTO.labels) &&
        Objects.equals(this.funnels, flowDTO.funnels);
  }

  @Override
  public int hashCode() {
    return Objects.hash(processGroups, remoteProcessGroups, processors, inputPorts, outputPorts, connections, labels, funnels);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FlowDTO {\n");
    
    sb.append("    processGroups: ").append(toIndentedString(processGroups)).append("\n");
    sb.append("    remoteProcessGroups: ").append(toIndentedString(remoteProcessGroups)).append("\n");
    sb.append("    processors: ").append(toIndentedString(processors)).append("\n");
    sb.append("    inputPorts: ").append(toIndentedString(inputPorts)).append("\n");
    sb.append("    outputPorts: ").append(toIndentedString(outputPorts)).append("\n");
    sb.append("    connections: ").append(toIndentedString(connections)).append("\n");
    sb.append("    labels: ").append(toIndentedString(labels)).append("\n");
    sb.append("    funnels: ").append(toIndentedString(funnels)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

