/*
 * NiFi Rest Api
 * The Rest Api provides programmatic access to command and control a NiFi instance in real time. Start and                                              stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * OpenAPI spec version: 1.3.0
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.github.hermannpencole.nifi.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * NodeEventDTO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-06-15T23:51:49.699+02:00")
public class NodeEventDTO {
  @SerializedName("timestamp")
  private String timestamp = null;

  @SerializedName("category")
  private String category = null;

  @SerializedName("message")
  private String message = null;

  public NodeEventDTO timestamp(String timestamp) {
    this.timestamp = timestamp;
    return this;
  }

   /**
   * The timestamp of the node event.
   * @return timestamp
  **/
  @ApiModelProperty(example = "null", value = "The timestamp of the node event.")
  public String getTimestamp() {
    return timestamp;
  }

  public void setTimestamp(String timestamp) {
    this.timestamp = timestamp;
  }

  public NodeEventDTO category(String category) {
    this.category = category;
    return this;
  }

   /**
   * The category of the node event.
   * @return category
  **/
  @ApiModelProperty(example = "null", value = "The category of the node event.")
  public String getCategory() {
    return category;
  }

  public void setCategory(String category) {
    this.category = category;
  }

  public NodeEventDTO message(String message) {
    this.message = message;
    return this;
  }

   /**
   * The message in the node event.
   * @return message
  **/
  @ApiModelProperty(example = "null", value = "The message in the node event.")
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NodeEventDTO nodeEventDTO = (NodeEventDTO) o;
    return Objects.equals(this.timestamp, nodeEventDTO.timestamp) &&
        Objects.equals(this.category, nodeEventDTO.category) &&
        Objects.equals(this.message, nodeEventDTO.message);
  }

  @Override
  public int hashCode() {
    return Objects.hash(timestamp, category, message);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NodeEventDTO {\n");
    
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    category: ").append(toIndentedString(category)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

