/*
 * NiFi Rest Api
 * The Rest Api provides programmatic access to command and control a NiFi instance in real time. Start and                                              stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * OpenAPI spec version: 1.5.0
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.github.hermannpencole.nifi.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.github.hermannpencole.nifi.swagger.client.model.ProcessGroupStatusSnapshotDTO;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ProcessGroupStatusSnapshotEntity
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-03-03T16:29:45.931+01:00")
public class ProcessGroupStatusSnapshotEntity {
  @SerializedName("id")
  private String id = null;

  @SerializedName("processGroupStatusSnapshot")
  private ProcessGroupStatusSnapshotDTO processGroupStatusSnapshot = null;

  @SerializedName("canRead")
  private Boolean canRead = null;

  public ProcessGroupStatusSnapshotEntity id(String id) {
    this.id = id;
    return this;
  }

   /**
   * The id of the process group.
   * @return id
  **/
  @ApiModelProperty(value = "The id of the process group.")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public ProcessGroupStatusSnapshotEntity processGroupStatusSnapshot(ProcessGroupStatusSnapshotDTO processGroupStatusSnapshot) {
    this.processGroupStatusSnapshot = processGroupStatusSnapshot;
    return this;
  }

   /**
   * Get processGroupStatusSnapshot
   * @return processGroupStatusSnapshot
  **/
  @ApiModelProperty(value = "")
  public ProcessGroupStatusSnapshotDTO getProcessGroupStatusSnapshot() {
    return processGroupStatusSnapshot;
  }

  public void setProcessGroupStatusSnapshot(ProcessGroupStatusSnapshotDTO processGroupStatusSnapshot) {
    this.processGroupStatusSnapshot = processGroupStatusSnapshot;
  }

   /**
   * Indicates whether the user can read a given resource.
   * @return canRead
  **/
  @ApiModelProperty(value = "Indicates whether the user can read a given resource.")
  public Boolean isCanRead() {
    return canRead;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProcessGroupStatusSnapshotEntity processGroupStatusSnapshotEntity = (ProcessGroupStatusSnapshotEntity) o;
    return Objects.equals(this.id, processGroupStatusSnapshotEntity.id) &&
        Objects.equals(this.processGroupStatusSnapshot, processGroupStatusSnapshotEntity.processGroupStatusSnapshot) &&
        Objects.equals(this.canRead, processGroupStatusSnapshotEntity.canRead);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, processGroupStatusSnapshot, canRead);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProcessGroupStatusSnapshotEntity {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    processGroupStatusSnapshot: ").append(toIndentedString(processGroupStatusSnapshot)).append("\n");
    sb.append("    canRead: ").append(toIndentedString(canRead)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

